### ISSUE TITLE
Post header images dissappeared in new version

### ISSUE THREAD

**Issue by mattdperkins** [max-holland/Peeves#25]
I've been migrating to a new server so upgrading Ghost and the Peeves theme - all my old posts have lost the header images. From this issue - 
https://github.com/mholland1337/Peeves/issues/21

I assume they are gone beecause now ghost has the functionality builtin. 

It looke like this pull was to fix it so that the first pic would still be used unless the header image is set in the ghost app itself:
https://github.com/mholland1337/Peeves/commit/03b76efbce60ee6c0730e79db4699643918e6ee0

And I have the lines in my init.main.js file but am not seeing them.
I have the blog running here: mattsrespite.com using ghost v0.5.3 and Peeves 2.1.5 with the header images showing.
And here: http://ghost.matthewdperkins.com with ghost v0.5.10 and Peeves 2.2 with no images showing. 
I exported the blog content from the old version and imported to the new - will soon be setting the correct urls so mattsrespite.com can point to the new server.

**Comment by sean-stanley** [comment]
I think you have to change all your posts to use the post image setting for setting the picture not just inserting an image to the beginning of the post. 

You set the post image by loading the post to edit and clicking the gear near the bottom to open up the settings pane, set the image in the top window of the settings pane and voila works again.

A good PR might be a fallback where if {{image}} is undefined use the first image of the post. Also an update to the documentation about the new way of having a post photo would be helpful.

**Comment by mattdperkins** [comment]
Unfortunately I started using Peeves before ghost had that functionality - and now I definitely can't go back and edit all my posts to upload the image as the new ghost version wants.   
So I've basically moved to a new theme that still shows the images in the older posts.

**Comment by oliverbenns** [comment]
Yeah I've had to go through all my posts and update them. Unfortunately @mattdperkins you're probably going to want to make the switchover at some point.

**Comment by weidwonder** [comment]
I've noticed that my post first image not taken to be the header image.
My blog is Ghost v6.3
